### ISSUE TITLE
Pre-selected protocols not updating

### ISSUE THREAD

**Issue by gbathree** [venturit/photosynq-app#12]
In the "quick measurement" start menu, when selecting your protocol, the protocols shown at the top are not those flagged 'pre-selected' by the database.  It appears (maybe) that the previous pre-selected protocols were hardcoded.  Any protocols which are flagged as pre-selected should be shown here.

**Comment by PatilTushar** [comment]
This bus is solved in [version 1.5](https://play.google.com/store/apps/details?id=com.photosynq.app&hl=en)
