### ISSUE TITLE
selecting user answers screen shows multiples of the same answer

### ISSUE THREAD

**Issue by gbathree** [venturit/photosynq-app#13]
See example below.  This should not duplicate each of the user answers.  This happened the first time I opened the project, so I'm not quite sure of the cause, but this also occurred on the previous version of the apk.  

![screenshot_2015-01-12-14-19-58](https://cloud.githubusercontent.com/assets/1742369/5709253/4fc568be-9a66-11e4-86b4-b9a31108113b.png)

**Comment by PatilTushar** [comment]
Clearing cache functionality is added in [version 1.5](https://play.google.com/store/apps/details?id=com.photosynq.app&hl=en)
