### ISSUE TITLE
prevent auto-dim during measurements

### ISSUE THREAD

**Issue by gbathree** [venturit/photosynq-app#15]
Is it possible to prevent auto-dim when the user is taking measurements, and when they are selecting through using answers (basically, any time after they have pressed the 'start').  User testing brought up this suggestion, and I think it's a good idea -

**Comment by PatilTushar** [comment]
Fixed and pushed code at [commit](https://github.com/venturit/photosynq-app/commit/137d27c9fa5f935fc4e0866d9399901121f1546a)
