### ISSUE TITLE
new data management framework in android app

### ISSUE THREAD

**Issue by gbathree** [venturit/photosynq-app#19]
I like the step towards integrating data management into 'options' button in the upper right side of the project page.  However, I think we can further simplify both the design and the user interface.  See image below for detailed new user experience for managing data.

![newest version](https://cloud.githubusercontent.com/assets/1742369/6693637/c5020e9a-ccaa-11e4-91ce-ed9d9470f221.png)

**Comment by gbathree** [comment]
I updated the image to include some of the concerns you had @galacto .  Now instead of pop-ups, the fixed value and incremented value screens are just normal screens, which means that users can access the 'options' button from them.  So when they click in the review screen on a fixed value, it returns them to the fixed value screen to either change the value, or click on the options button where they can choose a different user selected option ('enter text', 'fixed value', 'auto increment', or 'qr/bar code scan').

Obviously my screen design sucks :) but I think the flow is correct.  Let me know what you think.

**Comment by gbathree** [comment]
@galacto... ugh I rethought this and need some help on the UI.  Could we have a call this week to discuss quick... there's several ways to do this and I'm honestly just not sure which one is best, but it is quite important so I'd like some help thinking through it.

Greg

**Comment by galacto** [comment]
Sure @gbathree lets discuss and finalize this week

**Comment by PatilTushar** [comment]
Solved this issue in [version 2.2](https://play.google.com/store/apps/details?id=com.photosynq.app).
