### ISSUE TITLE
reset measurement device info on main menu bar when you hit clear cache

### ISSUE THREAD

**Issue by gbathree** [venturit/photosynq-app#20]
Test:

Connect to a device, note that the device appears on the main menu bar.  Now hit clear cache, and wait a moment for it to load.  The measurement device is reset to 'none', however, the previously connected device is still displayed in the main menu bar.  You can confirm this by clicking on quick measurement and taking a measurement - you will get the error that says 'multispeq not connected please configure multispeq first".

**Comment by gbathree** [comment]
Actually - let's just not reset the device with clear cache.  It's not very helpful and device connection isn't ever a problem at this point -

**Comment by PatilTushar** [comment]
fixed this issue.
