### ISSUE TITLE
get rid of side swipe in user selected data view

### ISSUE THREAD

**Issue by gbathree** [venturit/photosynq-app#21]
The current side swipe system when selecting through answers works fine, but the problem is users consistenly accidentally hit buttons on the screen while attempting to side swipe.  The first three users to use this in the new app have experienced this problem (!).

So, we should probably get rid of side swipe functionality and leave only the 'next' and 'previous' buttons until we can find an options which prevents accidental button pushes (unless you have another suggestion).

**Comment by PatilTushar** [comment]
Solved this issue in [version 2.1](https://play.google.com/store/apps/details?id=com.photosynq.app). pushed code at [commit](https://github.com/venturit/photosynq-app/commit/9311e59ef35606239c7bfec5edfc81243b405e53)
