### ISSUE TITLE
put user answers into image location

### ISSUE THREAD

**Issue by gbathree** [venturit/photosynq-app#22]
Currently, we only have the PhotosynQ logo as the default image for user answers.  A user suggested putting the answer text in the image by default if not image is specified.  

I think this is a good idea, and would make the selection choices more obvious and the actual text for selection larger... what do you think?

See example below:

![selection_183](https://cloud.githubusercontent.com/assets/1742369/6531747/6f41eb46-c409-11e4-8d01-6cb819295e4b.png)

**Comment by PatilTushar** [comment]
fixed this issue.
