### ISSUE TITLE
Update message when photosynq.org isn't available

### ISSUE THREAD

**Issue by gbathree** [venturit/photosynq-app#24]
Many users are getting confused when on networks which have web-portal logins to access the internet (like guest networks), and these tend to be at universities.  Updating the verbage in the error messages would address much of this problem:

First - can you make these messages stay up a little longer (maybe +5 seconds) so people have time to read them.  Then...

Currently, when no network is reachable available the app says "No network available!"
Change to: 
"You are not connect to a network.  
Check if wifi is turned on 
and if networks are available in your system settings screen."

When the server is unreachable AND , app says "PhotosynQ.org server is unreachable"
Change to: 
"PhotosynQ.org is unreachable.  
Check if your internet connection requires a password or sign in."

Currently, when you cannot connect via bluetooth, app says "unable to connect to device"
Change to: 
"unable to connect to device.  
Make sure device is powered on (device auto-shuts off after 2 min of inactivity).  
Check batteries if connection issues persist"

**Comment by PatilTushar** [comment]
Fixed and pushed code at [commit](https://github.com/venturit/photosynq-app/commit/c2f302f8ed331c4e6df50c55cef68f38c44d23f4)
