### ISSUE TITLE
offline mode not calling correct macros - not clearing cache correctly (?)

### ISSUE THREAD

**Issue by gbathree** [venturit/photosynq-app#4]
NOTE: This may be a data explorer issue, but I want to make sure I note it here -

You can see it if you run pass it on while online.  You should see the SPAD results showing spad and minolta spad from the macro.  However, when you are online, the SPAD results show the macro outputs for FINAL BETA chlorophyll fluorescence phi2 which is incorrect.  If you reconnect to the web, hit sync and try again, it goes back to displaying the SPAD results.

So somehow in the offline mode, the macro connections are not maintained correctly.

**Comment by kalpeshdeo** [comment]
Hello Greg,
The issue is only for protocols without macros. There is a fix in the cellphone.html. Please find attachment after the fix. It shows blank row for null macros. Is it ok to show blank row?

![screen shot 2015-01-08 at 1 56 09 am](https://cloud.githubusercontent.com/assets/9951874/5652841/cbd5d8ec-96da-11e4-8f40-7f438b5543fa.png)

**Comment by gbathree** [comment]
​Yes, blank row is fine.  We'll end up changing must of the structure of
this later, for now blank is fine.

Greg​


On Wed, Jan 7, 2015 at 3:35 PM, Kalpesh Deo <notifications@github.com>
wrote:

> Hello Greg,
> The issue is only for protocols without macros. There is a fix in the
> cellphone.html. Please find attachment after the fix. It shows blank row
> for null macros. Is it ok to show blank row?
>
> [image: screen shot 2015-01-08 at 1 56 09 am]
> <https://cloud.githubusercontent.com/assets/9951874/5652841/cbd5d8ec-96da-11e4-8f40-7f438b5543fa.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/venturit/photosynq-app/issues/4#issuecomment-69087463>
> .
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org

**Comment by gbathree** [comment]
Now there are multiple protocols which have no macros outputted at all!  Unclear of the issue, seems that protocol IDs are tagged correctly in the data, and protocols and macros are correctly associated.  Perhaps not all necessary macros are downloaded, so the macro applied is blank?

![screenshot_2015-01-12-15-06-43](https://cloud.githubusercontent.com/assets/1742369/5710208/268921ea-9a6e-11e4-92d3-2050d187751c.png)

**Comment by PatilTushar** [comment]
This issue is solved in [version 1.5](https://play.google.com/store/apps/details?id=com.photosynq.app&hl=en)
