### ISSUE TITLE
Autosynq not working

### ISSUE THREAD

**Issue by teravestdan** [venturit/photosynq-app#44]
App is uploading data via my cell data even though I checked 'auto-synq in Wifi range only.' I turned off the phone's wifi to ensure it wasn't sending data via wifi, and it still auto-synced the data.

**Comment by kalpeshdeo** [comment]
What is the version of an app?

**Comment by teravestdan** [comment]
I believe it is the newest version, I just installed it yesterday

**Comment by prabode** [comment]
@kalpeshdeo is there a version number on the app @teravestdan can provide us?

**Comment by kalpeshdeo** [comment]
Yes. Go to Settings -> Apps -> PHOTOSYNQ, In App Info it shows a version of an app.

**Comment by teravestdan** [comment]
Version 2.4, is that the newest version?

On Thu, May 21, 2015 at 4:35 PM, Kalpesh Deo <notifications@github.com>
wrote:

> Yes. Go to Settings -> Apps -> PHOTOSYNQ, In App Info it shows a version
> of an app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/venturit/photosynq-app/issues/44#issuecomment-104413483>
> .
>



-- 
Dan TerAvest, PhD
Washington State University
Plant Biology Lab
612 Wilson Rd, Room S202
East Lansing  MI 48824 US
Tel: +1 616 552 2923

**Comment by gbathree** [comment]
​I also have 2.4​


On Thu, May 21, 2015 at 4:37 PM, teravestdan <notifications@github.com>
wrote:

> Version 2.4, is that the newest version?
>
> On Thu, May 21, 2015 at 4:35 PM, Kalpesh Deo <notifications@github.com>
> wrote:
>
> > Yes. Go to Settings -> Apps -> PHOTOSYNQ, In App Info it shows a version
> > of an app.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/venturit/photosynq-app/issues/44#issuecomment-104413483
> >
> > .
> >
>
>
>
> --
> Dan TerAvest, PhD
> Washington State University
> Plant Biology Lab
> 612 Wilson Rd, Room S202
> East Lansing MI 48824 US
> Tel: +1 616 552 2923
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/venturit/photosynq-app/issues/44#issuecomment-104413924>
> .
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org
