### ISSUE TITLE
Not syncing all data

### ISSUE THREAD

**Issue by teravestdan** [venturit/photosynq-app#45]
Not all of the data is being synced to the server after being cached. For example, I took 14 data points, when I synced, 12 data points synced while 2 data points failed to sync.

**Comment by kalpeshdeo** [comment]
Can you please open the data points and send the screenshots?

**Comment by gbathree** [comment]
I think we got it figured out.  See the email I just sent out.  We'll
validate the json, and change the user experience so they cannot re-measure
after cancelling - they must wait until you receive confirmation of cancel
first form the device (double carriage return).

Greg

On Fri, May 22, 2015 at 9:25 AM, Kalpesh Deo <notifications@github.com>
wrote:

> Can you please open the data points and send the screenshots?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/venturit/photosynq-app/issues/45#issuecomment-104660151>
> .
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org
